package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1



/**
 * Crnalista generated by hbm2java
 */
public class Crnalista  implements java.io.Serializable {


     private Integer idCrnaLista;
     private Integer idKorisnik;

    public Crnalista() {
    }

    public Crnalista(Integer idKorisnik) {
       this.idKorisnik = idKorisnik;
    }
   
    public Integer getIdCrnaLista() {
        return this.idCrnaLista;
    }
    
    public void setIdCrnaLista(Integer idCrnaLista) {
        this.idCrnaLista = idCrnaLista;
    }
    public Integer getIdKorisnik() {
        return this.idKorisnik;
    }
    
    public void setIdKorisnik(Integer idKorisnik) {
        this.idKorisnik = idKorisnik;
    }




}


