package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Integer idFestival;
     private String naziv;
     private String mesto;
     private String statusFestival;
     private Date datumPocetka;
     private Date datumKraja;
     private BigDecimal cena;
     private String kratakOpis;
     private String mestaOdrzavanja = "";
     private String datumPocetkaLepo = "";
     private String datumKrajaLepo = "";

    public Festival() {
    }

    public Festival(String naziv, String mesto, String statusFestival, Date datumPocetka, Date datumKraja, BigDecimal cena, String kratakOpis) {
       this.naziv = naziv;
       this.mesto = mesto;
       this.statusFestival = statusFestival;
       this.datumPocetka = datumPocetka;
       this.datumKraja = datumKraja;
       this.cena = cena;
       this.kratakOpis = kratakOpis;
    }
   
    public Integer getIdFestival() {
        return this.idFestival;
    }
    
    public void setIdFestival(Integer idFestival) {
        this.idFestival = idFestival;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public String getStatusFestival() {
        return this.statusFestival;
    }
    
    public void setStatusFestival(String statusFestival) {
        this.statusFestival = statusFestival;
    }
    public Date getDatumPocetka() {
        return this.datumPocetka;
    }
    
    public void setDatumPocetka(Date datumPocetka) {
        this.datumPocetka = datumPocetka;
    }
    public Date getDatumKraja() {
        return this.datumKraja;
    }
    
    public void setDatumKraja(Date datumKraja) {
        this.datumKraja = datumKraja;
    }
    public BigDecimal getCena() {
        return this.cena;
    }
    
    public void setCena(BigDecimal cena) {
        this.cena = cena;
    }
    public String getKratakOpis() {
        return this.kratakOpis;
    }
    
    public void setKratakOpis(String kratakOpis) {
        this.kratakOpis = kratakOpis;
    }

    public String getMestaOdrzavanja() {
        return mestaOdrzavanja;
    }

    public void setMestaOdrzavanja(String mestaOdrzavanja) {
        this.mestaOdrzavanja = mestaOdrzavanja;
    }

    public String getDatumPocetkaLepo() {
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
        this.datumPocetkaLepo = sdf.format(datumPocetka);
        return this.datumPocetkaLepo;
    }

    public void setDatumPocetkaLepo(String datumPocetkaLepo) {
        this.datumPocetkaLepo = datumPocetkaLepo;
    }

    public String getDatumKrajaLepo() {
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
        this.datumKrajaLepo = sdf.format(datumKraja);
        return this.datumKrajaLepo;
    }

    public void setDatumKrajaLepo(String datumKrajaLepo) {
        this.datumKrajaLepo = datumKrajaLepo;
    }

    


}


