package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private Integer idFilm;
     private String naziv;
     private String originalniNaziv;
     private String slikaPoster;
     private String reziser;
     private String kratakOpis;
     private String godina;
     private String glavniGlumci;
     private String trajanje;
     private String zemljaPorekla;
     private String linkImdb;
     private String linkRotten;
     private String linkTrailer;
     private double rejting;
     private Integer brojOcena;

    public Film() {
    }

    public Film(String naziv, String originalniNaziv, String slikaPoster, String reziser, String kratakOpis, String glavniGlumci, String trajanje, String zemljaPorekla, String linkImdb, String linkRotten, String linkTrailer, double rejting, Integer brojOcena) {
       this.naziv = naziv;
       this.originalniNaziv = originalniNaziv;
       this.slikaPoster = slikaPoster;
       this.reziser = reziser;
       this.kratakOpis = kratakOpis;
       this.glavniGlumci = glavniGlumci;
       this.trajanje = trajanje;
       this.zemljaPorekla = zemljaPorekla;
       this.linkImdb = linkImdb;
       this.linkRotten = linkRotten;
       this.linkTrailer = linkTrailer;
       this.rejting = rejting;
       this.brojOcena = brojOcena;
    }
   
    public Integer getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(Integer idFilm) {
        this.idFilm = idFilm;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getOriginalniNaziv() {
        return this.originalniNaziv;
    }
    
    public void setOriginalniNaziv(String originalniNaziv) {
        this.originalniNaziv = originalniNaziv;
    }
    public String getSlikaPoster() {
        return this.slikaPoster;
    }
    
    public void setSlikaPoster(String slikaPoster) {
        this.slikaPoster = slikaPoster;
    }
    public String getReziser() {
        return this.reziser;
    }
    
    public void setReziser(String reziser) {
        this.reziser = reziser;
    }
    public String getKratakOpis() {
        return this.kratakOpis;
    }
    
    public void setKratakOpis(String kratakOpis) {
        this.kratakOpis = kratakOpis;
    }

    public String getGodina() {
        return godina;
    }

    public void setGodina(String godina) {
        this.godina = godina;
    }
    
    
    public String getGlavniGlumci() {
        return this.glavniGlumci;
    }
    
    public void setGlavniGlumci(String glavniGlumci) {
        this.glavniGlumci = glavniGlumci;
    }
    public String getTrajanje() {
        return this.trajanje;
    }
    
    public void setTrajanje(String trajanje) {
        this.trajanje = trajanje;
    }
    public String getZemljaPorekla() {
        return this.zemljaPorekla;
    }
    
    public void setZemljaPorekla(String zemljaPorekla) {
        this.zemljaPorekla = zemljaPorekla;
    }
    public String getLinkImdb() {
        return this.linkImdb;
    }
    
    public void setLinkImdb(String linkImdb) {
        this.linkImdb = linkImdb;
    }
    public String getLinkRotten() {
        return this.linkRotten;
    }
    
    public void setLinkRotten(String linkRotten) {
        this.linkRotten = linkRotten;
    }
    public String getLinkTrailer() {
        return this.linkTrailer;
    }
    
    public void setLinkTrailer(String linkTrailer) {
        this.linkTrailer = linkTrailer;
    }
    public double getRejting() {
        return this.rejting;
    }
    
    public void setRejting(double rejting) {
        this.rejting = rejting;
    }
    public Integer getBrojOcena() {
        return this.brojOcena;
    }
    
    public void setBrojOcena(Integer brojOcena) {
        this.brojOcena = brojOcena;
    }




}


