package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1



/**
 * Komentar generated by hbm2java
 */
public class Komentar  implements java.io.Serializable {


     private Integer idKomentar;
     private String sadrzaj;
     private Integer idFilm;
     private Integer idKorisnik;

    public Komentar() {
    }

    public Komentar(String sadrzaj, Integer idFilm) {
       this.sadrzaj = sadrzaj;
       this.idFilm = idFilm;
    }
   
    public Integer getIdKomentar() {
        return this.idKomentar;
    }
    
    public void setIdKomentar(Integer idKomentar) {
        this.idKomentar = idKomentar;
    }
    public String getSadrzaj() {
        return this.sadrzaj;
    }
    
    public void setSadrzaj(String sadrzaj) {
        this.sadrzaj = sadrzaj;
    }
    public Integer getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(Integer idFilm) {
        this.idFilm = idFilm;
    }

    public Integer getIdKorisnik() {
        return idKorisnik;
    }

    public void setIdKorisnik(Integer idKorisnik) {
        this.idKorisnik = idKorisnik;
    }




}


