package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1



/**
 * Mestoodrzavanja generated by hbm2java
 */
public class Mestoodrzavanja  implements java.io.Serializable {


     private Integer idMesto;
     private String nazivMesta;
     private String lokacija;
     private int idFestival;

    public Mestoodrzavanja() {
    }

	
    public Mestoodrzavanja(int idFestival) {
        this.idFestival = idFestival;
    }
    public Mestoodrzavanja(String nazivMesta, String lokacija, int idFestival) {
       this.nazivMesta = nazivMesta;
       this.lokacija = lokacija;
       this.idFestival = idFestival;
    }
   
    public Integer getIdMesto() {
        return this.idMesto;
    }
    
    public void setIdMesto(Integer idMesto) {
        this.idMesto = idMesto;
    }
    public String getNazivMesta() {
        return this.nazivMesta;
    }
    
    public void setNazivMesta(String nazivMesta) {
        this.nazivMesta = nazivMesta;
    }
    public String getLokacija() {
        return this.lokacija;
    }
    
    public void setLokacija(String lokacija) {
        this.lokacija = lokacija;
    }
    public int getIdFestival() {
        return this.idFestival;
    }
    
    public void setIdFestival(int idFestival) {
        this.idFestival = idFestival;
    }




}


