package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1



/**
 * Ocena generated by hbm2java
 */
public class Ocena  implements java.io.Serializable {


     private Integer idOcena;
     private Integer ocena;
     private Integer idFilm;
     private Integer idKorisnik;

    public Ocena() {
    }

    public Ocena(Integer ocena, Integer idFilm) {
       this.ocena = ocena;
       this.idFilm = idFilm;
    }
   
    public Integer getIdOcena() {
        return this.idOcena;
    }
    
    public void setIdOcena(Integer idOcena) {
        this.idOcena = idOcena;
    }
    public Integer getOcena() {
        return this.ocena;
    }
    
    public void setOcena(Integer ocena) {
        this.ocena = ocena;
    }
    public Integer getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(Integer idFilm) {
        this.idFilm = idFilm;
    }

    public Integer getIdKorisnik() {
        return idKorisnik;
    }

    public void setIdKorisnik(Integer idKorisnik) {
        this.idKorisnik = idKorisnik;
    }

    
    


}


