package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Rezervacija generated by hbm2java
 */
public class Rezervacija  implements java.io.Serializable {


     private Integer idRezervacija;
     private String jedinstveniKod;
     private Date datumRezervacije;
     private String statusRezervacije;
     private Integer brojRezervacija;
     private Integer idKorisnik;
     private Integer idProjekcija;
     private String datumLepo = "";
     private Projekcija projekcija = null;
     private String imeKorisnika = "";
     private String prezimeKorisnika = "";
     
    public Rezervacija() {
    }

    public Rezervacija(String jedinstveniKod, Date datumRezervacije, String statusRezervacije, Integer brojRezervacija, Integer idKorisnik, Integer idProjekcija) {
       this.jedinstveniKod = jedinstveniKod;
       this.datumRezervacije = datumRezervacije;
       this.statusRezervacije = statusRezervacije;
       this.brojRezervacija = brojRezervacija;
       this.idKorisnik = idKorisnik;
       this.idProjekcija = idProjekcija;
    }
   
    public Integer getIdRezervacija() {
        return this.idRezervacija;
    }
    
    public void setIdRezervacija(Integer idRezervacija) {
        this.idRezervacija = idRezervacija;
    }
    public String getJedinstveniKod() {
        return this.jedinstveniKod;
    }
    
    public void setJedinstveniKod(String jedinstveniKod) {
        this.jedinstveniKod = jedinstveniKod;
    }
    public Date getDatumRezervacije() {
        return this.datumRezervacije;
    }
    
    public void setDatumRezervacije(Date datumRezervacije) {
        this.datumRezervacije = datumRezervacije;
    }
    public String getStatusRezervacije() {
        return this.statusRezervacije;
    }
    
    public void setStatusRezervacije(String statusRezervacije) {
        this.statusRezervacije = statusRezervacije;
    }
    public Integer getBrojRezervacija() {
        return this.brojRezervacija;
    }
    
    public void setBrojRezervacija(Integer brojRezervacija) {
        this.brojRezervacija = brojRezervacija;
    }
    public Integer getIdKorisnik() {
        return this.idKorisnik;
    }
    
    public void setIdKorisnik(Integer idKorisnik) {
        this.idKorisnik = idKorisnik;
    }
    public Integer getIdProjekcija() {
        return this.idProjekcija;
    }
    
    public void setIdProjekcija(Integer idProjekcija) {
        this.idProjekcija = idProjekcija;
    }

    public String getDatumLepo() {
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy HH:mm");
        this.datumLepo = sdf.format(datumRezervacije);
        return this.datumLepo;
    }

    public void setDatumLepo(String datumLepo) {
        this.datumLepo = datumLepo;
    }

    public Projekcija getProjekcija() {
        return projekcija;
    }

    public void setProjekcija(Projekcija projekcija) {
        this.projekcija = projekcija;
    }

    public String getImeKorisnika() {
        return imeKorisnika;
    }

    public void setImeKorisnika(String imeKorisnika) {
        this.imeKorisnika = imeKorisnika;
    }

    public String getPrezimeKorisnika() {
        return prezimeKorisnika;
    }

    public void setPrezimeKorisnika(String prezimeKorisnika) {
        this.prezimeKorisnika = prezimeKorisnika;
    }
    
    

    
    


}


