package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1



/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer idSala;
     private String naziv;
     private Integer idMesto;

    public Sala() {
    }

    public Sala(String naziv, Integer idMesto) {
       this.naziv = naziv;
       this.idMesto = idMesto;
    }
   
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Integer getIdMesto() {
        return this.idMesto;
    }
    
    public void setIdMesto(Integer idMesto) {
        this.idMesto = idMesto;
    }




}


