package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1

import org.primefaces.model.StreamedContent;




/**
 * Slikafilm generated by hbm2java
 */
public class Slikafilm  implements java.io.Serializable {


     private Integer idSlika;
     private String naziv;
     private String slika;
     private Integer idFilm;
     private StreamedContent content;

    public Slikafilm() {
    }

    public Slikafilm(String naziv, String slika, Integer idFilm) {
       this.naziv = naziv;
       this.slika = slika;
       this.idFilm = idFilm;
    }
   
    public Integer getIdSlika() {
        return this.idSlika;
    }
    
    public void setIdSlika(Integer idSlika) {
        this.idSlika = idSlika;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getSlika() {
        return this.slika;
    }
    
    public void setSlika(String slika) {
        this.slika = slika;
    }
    public Integer getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(Integer idFilm) {
        this.idFilm = idFilm;
    }

    public StreamedContent getContent() {
        return content;
    }

    public void setContent(StreamedContent content) {
        this.content = content;
    }

    


}


