package beans;
// Generated Jan 21, 2018 2:00:58 AM by Hibernate Tools 4.3.1



/**
 * Zahtevregistracija generated by hbm2java
 */
public class Zahtevregistracija  implements java.io.Serializable {


     private Integer idZahtev;
     private String username;
     private String lozinka;
     private String ime;
     private String prezime;
     private String kontakt;
     private String email;

    public Zahtevregistracija() {
    }

    public Zahtevregistracija(String username, String lozinka, String ime, String prezime, String kontakt, String email) {
       this.username = username;
       this.lozinka = lozinka;
       this.ime = ime;
       this.prezime = prezime;
       this.kontakt = kontakt;
       this.email = email;
    }
   
    public Integer getIdZahtev() {
        return this.idZahtev;
    }
    
    public void setIdZahtev(Integer idZahtev) {
        this.idZahtev = idZahtev;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getKontakt() {
        return this.kontakt;
    }
    
    public void setKontakt(String kontakt) {
        this.kontakt = kontakt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


